// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";

/// @title CounterTest
/// @author Pilar (adapted)
/// @notice Unit tests for the `Counter` contract using Foundry's Forge test framework.
/// @dev Demonstrates setup, deterministic testing, and fuzz testing.
contract CounterTest is Test {
    /// @notice Instance of the Counter contract under test.
    Counter public counter;

    /// @notice Deploys a new Counter contract and sets its initial value to zero.
    /// @dev This function runs automatically before each test (Foundry’s `setUp()` convention).
    function setUp() public {
        counter = new Counter();
        counter.setNumber(0);
    }

    /// @notice Tests that calling `increment()` increases the stored number by 1.
    /// @dev Asserts that the number after increment equals 1 when starting from 0.
    function test_Increment() public {
        counter.increment();
        assertEq(counter.number(), 1);
    }

    /// @notice Fuzz test that verifies `setNumber()` correctly stores any arbitrary value.
    /// @dev Foundry’s fuzzing engine supplies random values for `x` to test function robustness.
    /// @param x Random unsigned integer value generated by Foundry’s fuzzer.
    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
}
